examples/web/index.html, package.json, src/common.ts, src/common/ant.ts, src/common/ar-io.ts, src/common/arweave.ts, src/common/contracts/warp-contract.ts, src/common/warp.ts, src/utils/smartweave.ts, tests/integration/ant.test.ts, tests/integration/ar-io.test.ts, tests/unit/utils-smartweave.test.ts, tsconfig.web.json
If you don't specify anything - the `ArIO.init()` will throw `Invalid configuration error` as `{}` is provided by default. This PR aims to cleanup types and leverage generics where useful. Additionally separates out warp and arweave into separate files - we may need to move these to web and node implementations to avoid some build errors in the browser.
=> fix(types): use generic types and make config optional on `init` for ArIO client

src/common/contracts/warp-contract.ts, tests/integration/ant-writable.test.ts, tests/integration/ar-io-writable.test.ts
=> fix(PE-6058): fix signing issues with write interactions

bundle.mjs, docker-compose.yaml, package.json, src/common.ts, src/common/arweave.ts, src/common/logger.ts, src/node/index.ts, src/web/index.ts, yarn.lock
Winston does not play nice in web, and requires additional polyfills. bunyan is feature-par and is more suited for web environments. 
Additionally - this removes `utils` exported that are only needed internally. It also directly maps the `arweave` to use the node implementation.
=> fix(logger): replace winston with bunyan

src/constants.ts
* Adds a FQDN_REGEX that matches the one used in the ArNS contract (useful for clients to use for validation)
=> fix(utils): add FQDN regex

src/token.ts, tests/unit/token.test.ts
This makes it so you can easily print the value of the IOToken and mIOToken classes without having to use `.valueOf()` everytime. FWIW - mIOToken had this but IOToken did not. Added unit tests to show the usefulness.
=> chore(token): add symbol functions to print classes as their values

README.md, src/common.ts, src/common/ar-io.ts, tests/integration/ar-io-writable.test.ts, tests/integration/arlocal/ar-io-contract/index.js, tests/integration/jest.setup.ts, tests/utils.ts
Allows `mIOToken` class to be provided as an input parameter to write interaction APIs.
=> fix(mIO): allow mIO as an input to write APIs

package.json, src/common/io.ts, src/utils/graphql/processes.ts
This will avoid issues with clients using the newest AO implementation and unintentionally using the devnet process.
=> fix(io): default the IO process to use testnet

README.md, bundle.mjs, package.json, src/common/logger.ts, yarn.lock
Bunyan tries to work in the browser, but it has issues with extensions so reverting back to an updated winston that uses the console export by default
=> fix(log): replace bunyan with winston to ensure browser compatibility

README.md, src/io.ts, tests/e2e/cjs/index.test.js, tests/e2e/esm/index.test.js
The PR in the IO process adds weights to gateways and updates them on every new epoch.
Reference: https://github.com/ar-io/ar-io-network-process/pull/29
Example:
```typescript
const gateway = await io.getGateway({ address: "1H7WZIWhzwTH9FIcnuMqYkTsoyv1OTfGa_amvuYwrgo" })
```
Result:
```json
{
"vaults": [],
"startTimestamp": 1719295200000,
"endTimestamp": 0,
"totalDelegatedStake": 1200000000,
"operatorStake": 250000000012,
"status": "joined",
"observerAddress": "1H7WZIWhzwTH9FIcnuMqYkTsoyv1OTfGa_amvuYwrgo",
"weights": {
"compositeWeight": 0.97688888893556,
"gatewayRewardRatioWeight": 1,
"tenureWeight": 0.19444444444444,
"observerRewardRatioWeight": 1,
"normalizedCompositeWeight": 0.19247316211083,
"stakeWeight": 5.02400000024
},
"stats": {
"failedEpochCount": 0,
"failedConsecutiveEpochs": …
```
=> fix(types): update AoGateway type to include weights

src/io.ts
The new snapshots set eligible rewards at the beginning of the epoch. Distributions are added after the epoch ends
Related: https://github.com/ar-io/ar-io-network-process/pull/44
=> fix(types): update types for epoch distributions

README.md, examples/esm/index.mjs, examples/vite/package.json, examples/vite/src/App.css, examples/vite/src/App.tsx, examples/vite/src/index.css, examples/vite/yarn.lock, package.json, src/common/ant.ts, src/common/io.ts, src/types/ant.ts, src/types/io.ts, tests/e2e/cjs/index.test.js, tests/e2e/esm/index.test.js
Updated the `examples/vite` to show a chart for auction information using the read APIs. 
Related process PR - https://github.com/ar-io/ar-io-network-process
=> feat(auctions): add auctions api to IO classes

src/utils/processes.ts
The ArNSEventEmitter was strict checking states on ant retrieval - this requires configuration if we want to still retrieve those ants. Added a check on the constructor to allow for invalid or out of date ants to be returned.
=> fix(arns emitter): provide configuration for strict check

src/common/contracts/ao-process.ts, src/utils/base64.ts, tests/unit/b64.test.ts
this will produce non-deterministic IDs for all signer types that dont provide salt
PE-7158
=> fix(eth signer): use a unique anchor in ans-104 headers

src/types/common.ts, tests/e2e/esm/index.test.ts
```sh
~/ar-io/ar-io-sdk PE-7307-forw..primary-name                                                              19s 11:39:33 AM
> node lib/esm/cli/cli.js get-primary-name --name arns --dev
{
"owner": "HwFceQaMQnOBgKDpnFqCqgwKwEU5LBme1oXRuQOWSRA",
"startTimestamp": 1719356032297,
"processId": "HwFceQaMQnOBgKDpnFqCqgwKwEU5LBme1oXRuQOWSRA",
"name": "arns"
}
```
=> feat(primary names): add processID to read APIs PE-7307

src/common/contracts/ao-process.ts
msg.Error level read error before change
```sh
> ar.io get-token-cost --name anevenbetteridea --years 8 --dev --debug
{"level":"debug","message":"Evaluating read interaction on contract","name":"ar-io-sdk","tags":[{"name":"Action","value":"Token-Cost"},{"name":"Intent","value":"Buy-Record"},{"name":"Name","value":"anevenbetteridea"},{"name":"Years","value":"8"},{"name":"Purchase-Type","value":"lease"},{"name":"Timestamp","value":"1734545746000"}],"timestamp":"2024-12-18T18:23:34.569Z","version":"3.1.0-alpha.3"}
{"level":"debug","message":"Read interaction result","name":"ar-io-sdk","result":{"Assignments":[],"Error":"[string \"aos\"]:1464: [string \"aos\"]:9529: Timestamp must be greater than or equal to the last known message timestamp of 1734545971645 but was …
```
=> fix: format process errors to be more user friendly PE-7327

src/cli/cli.ts, src/common/contracts/ao-process.ts, src/common/io.ts, src/types/io.ts, src/utils/ao.ts, src/utils/arweave.ts, tests/e2e/esm/index.test.ts
The process now posts `Epoch-Distribution-Notice` messages with full distributed epoch data. We can fetch these via gql/gateway instead of persisting them in process state.
Related - https://github.com/ar-io/ar-io-network-process/pull/322
=> feat(io): fetch historical epoch data from gql

.vscode/settings.json, package.json, src/common/ant-registry.ts, src/common/ant.ts, src/common/io.ts, src/types/common.ts, src/types/io.ts, tests/e2e/cjs/index.test.ts, tests/e2e/cjs/package.json, tests/e2e/cjs/yarn.lock, tests/e2e/docker-compose.test.yml, tests/e2e/esm/index.test.ts, tests/e2e/esm/package.json, tests/e2e/esm/yarn.lock, tests/e2e/web/src/App.tsx, yarn.lock
I introduced a bug when adding `arweave` as an optional type in https://github.com/ar-io/ar-io-sdk/pull/337. It's easy to overlook what our overloaded `init` functions expect. This hopefully introduces new types that can be extended if/when necessary. Additionally, i've added e2e tests validating the instance types returned for all major classes. We can look to leverage unit tests more to avoid the entire docker setup when doing these simple type validations/checks.
=> fix(types): simplify types for init functions, cleanup contructors

src/cli/commands/readCommands.ts, src/cli/utils.ts, src/common/io.ts, src/types/io.ts, tests/e2e/esm/index.test.ts
=> fix(pagination): allow nested keys in sortBy pagination params utility type PE-7428

README.md, src/types/io.ts, tests/e2e/esm/index.test.ts
Depends on https://github.com/ar-io/ar-io-network-process/pull/341
=> fix(PE-7040): updated weight names

src/constants.ts
This brings in the fix for backwards compatibility in the ANT re: Handlers.once
=> fix(module ids): update ant lua and module id to ant 14

src/common/ant.ts, src/types/ant.ts, tests/e2e/esm/index.test.ts
This returns the additional index flag, indicating the position for each undername of an ANT.
=> feat(ant): add sorting to ANT records responses by default

CLI.md, README.md, examples/cjs/index.cjs, examples/esm/index.mjs, src/cli/utils.ts, src/common/ant.ts, src/common/io.ts, src/utils/arweave.ts, src/utils/processes.ts
fix(mainnet): default to the mainnet process ID
=> chore: release 3.8.1

src/common/contracts/ao-process.ts, src/types/common.ts
For AoProcess, only treat exceptions from ao.dryrun(), ao.message(), and ao.result() as retry-able errors. All other errors are treated as valid results from the process.
=> fix(PE-7718): improved retry logic

src/common/contracts/ao-process.ts, src/common/io.ts, src/utils/arweave.ts
If the epoch distribution message does not get cranked, we need to fallback to to the CU to with any tick messages that couldve created it and parse the results of those messages. This is a temporary patch, while we work with FWD to resolve
=> fix(gql): add fallback to go to CU for epoch distribution data

src/common/io.ts, src/common/turbo.ts, src/types/common.ts, src/web/index.ts
Modifies the turbo arns class to have authenticated and unauthenticated versions, updates signer to be more restricted types based on the message signing we have implmented.
Would like to add some stronger typing on the ARIO writable class to indicate on apis with `fundFrom: "turbo"` whether or not they can be used with turbo base on the class configuration.
=> PE-7751 config changes

CLI.md, README.md, src/cli/cli.ts, src/cli/commands/readCommands.ts, src/common/ant.ts, src/common/io.ts, src/types/ant.ts, src/types/io.ts, tests/e2e/esm/index.test.ts
This interface can be impemented in various ways. For now just adds resolution API directly via CUs on ARIO class. Wayfinder can also implement it, using router strategies to resolve arns names against ar-io resolver endpoints.
CLI:
```bash
❯ node lib/esm/cli/cli.js resolve-arns-name --name dtf
{
"name": "dtf",
"owner": "ZjmB2vEUlHlJ7-rgJkYP09N5IzLPhJyStVrK5u9dDEo",
"txId": "Zkoo3vgTq-f0wBlM-cOYhVy3dxVMajr7l-dEBFRYos4",
"ttlSeconds": 3600,
"recordIndex": 0,
"processId": "Rfm9Ob2M-7FRKdi4azJVU4JLpUa6bjM1Ud3KpwkepOE",
"undernameLimit": 10,
"type": "permabuy"
}
```
=> feat(arns): add ArNSNameResovler interface and API 

README.md, package.json, src/cli/utils.ts, src/common/contracts/ao-process.ts, src/common/io.ts, src/utils/ao.ts, src/utils/processes.ts, tests/e2e/cjs/package.json, tests/e2e/cjs/yarn.lock, tests/e2e/esm/index.test.ts, tests/e2e/esm/package.json, tests/e2e/esm/yarn.lock, tests/e2e/web/package.json, tests/e2e/web/src/App.tsx, tests/e2e/web/yarn.lock, tests/integration/package.json, yarn.lock
connect() now requires MODE to be set. Defaulting to legacy as all our processes still rely on CUs for evalution.
=> fix(deps): update aoconnect and add required MODE

src/common/wayfinder/wayfinder.test.ts, src/common/wayfinder/wayfinder.ts
The resolveWayfinderUrl function was incorrectly testing the entire path against the ARNS regex instead of just the name portion. This caused URLs like ar://cookbook_ao/welcome/getting-started.html to fail ARNS validation because the regex was testing cookbook_ao/welcome/getting-started.html instead of just cookbook_ao.
Changes: - Split path into name and remaining components before regex testing - Test only the first part against txIdRegex and arnsRegex - Improve URL construction to properly handle paths with and without additional components - Maintain backward compatibility for existing functionality
Fixes routing for ARNS names that include path components while preserving all existing behavior for transaction IDs and simple ARNS names.
=> fix(wayfinder): resolve ARNS names with path components correctly

WAYFINDER.md, examples/vite/src/App.tsx, examples/vite/src/components/Wayfinder.tsx, src/common/wayfinder/wayfinder.test.ts, src/common/wayfinder/wayfinder.ts
Some notes:
- fetch is native in both node and all major browsers - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
- handling ReadableStreams exclusively is easier than checking the type of responses returned by other http clients, and reduces edge cases for issues
- ReadableStreams are generally easy to work with when adding event flows and notifications, as you have finer grain control of data flowing and they are portable for both node and web environments
This is technically a breaking change, but since we are in beta and fetch is used by default, those using it with custom clients will have to fix.
=> fix(wayfinder): use native fetch http client for allr requests,
