ar-io/ar-io-sdk

examples/vite/package.json
examples/vite/src/App.tsx
examples/vite/yarn.lock
tsconfig.cjs.json

The alias is not doing what i thought it would.

chore(docs): update vite example and remove alias in tsconfig

---

CHANGELOG.md
examples/vite/README.md
examples/vite/package.json
examples/vite/yarn.lock
examples/web/index.html
examples/webpack/README.md
package.json
src/version.ts

Includes a warp patch that was creating build issues in web environments. 
https://github.com/warp-contracts/warp/issues/519

chore: release v1.0.6

---

src/common.ts
src/common/ar-io.ts
src/contract-state.ts

Replaces - https://github.com/ar-io/ar-io-sdk/pull/78

fix(P-6319): fix types for join network, add observer wallet

---

README.md
src/constants.ts
src/token.ts
src/types.ts
tests/unit/token.test.ts

These are helper classes to easily convert between mIO and IO

fix(token): add mIO and IO token classes to exports

---

docker-compose.yaml
jest.config.mjs
jest.integration.config.mjs
package.json
src/common/contracts/warp-contract.ts
tests/utils.ts
yarn.lock

This should speed up test execution and remove the flakiness in tests (at least to a degree)

fix(warp): bump warp version, fix jest setup

---

package.json
src/utils/http-client.ts
yarn.lock

This should help alleviate issues when requesting data from the service.

fix(axios): add back axios-retry

---

CHANGELOG.md
package.json
src/version.ts

chore: main back to alpha

---

examples/esm/index.mjs
src/common.ts
src/common/ant-ao.ts
src/common/ant.ts
src/common/ar-io.ts
src/common/contracts/ao-process.ts
src/common/index.ts
src/io.ts
src/utils/graphql/index.ts
src/utils/graphql/processes.ts
src/web/index.ts

Supports ANT apis for the ar-io-ant-process spec defined here https://github.com/ar-io/ar-io-ant-process

feat(ants): support ANT apis in SDK

---

package.json
src/utils/graphql/processes.ts
yarn.lock

Simple enough for now, we can add more robust GQL "best effort" search when we have a good tag structure.

fix(PE-6312): util for fetching ANT contracts

---

src/common/ant-ao.ts
src/common/io.ts
src/io.ts

Related to: https://github.com/ar-io/ar-io-network-process/pull/6

fix(tags): use updated ans-116 tag format for actions

---

README.md
src/common/io.ts
src/io.ts
tests/e2e/cjs/index.test.js
tests/e2e/cjs/package.json
tests/e2e/esm/index.test.js
tests/e2e/esm/package.json

The process computes this value based on its local state

fix(PE-6443): add api that returns the total token supply

---

src/common/ant-registry.ts
src/common/contracts/ao-process.ts
src/common/index.ts
src/constants.ts
src/io.ts
src/utils/ao.ts
src/utils/json.ts
src/utils/processes.ts
tests/e2e/cjs/index.test.js
tests/e2e/esm/index.test.js
tests/e2e/web/src/App.test.tsx
tests/e2e/web/src/App.tsx

feat(PE-6516): ant registry class

---

package.json
tests/e2e/cjs/index.test.js
tests/e2e/docker-compose.test.yml
tests/e2e/esm/index.test.js
tests/e2e/web/package.json
tests/e2e/web/src/App.test.tsx
tests/e2e/web/src/App.tsx
tests/e2e/web/yarn.lock
yarn.lock

This will give more durability in our tests and avoid going to in-network CUs unnecessarily

chore(test): use local cu with testcontainers for e2e tests

---

README.md
package.json
src/common.ts
src/node/index.ts
src/utils/ao.ts
src/web/index.ts
yarn.lock

fix(deps): update arbundles to @dha-team/arbundles

---

src/constants.ts
yarn.lock

…0-J0
Related changes: https://github.com/ar-io/ar-io-ant-process/pull/11

fix(ants): bump lua txid to zeglqubvIKvBEZaxAUuenLGGtQ1pJp9LZjd5hDe0-J0

---

src/io.ts

These services represent additional services operators provide for bundling and eventually payment

fix(types): update gateways to include services

---

src/common/io.ts
src/types/io.ts

We may change this to `upgradeName` or something else

feat(arns): add upgradeRecord API

---

src/common/io.ts
src/types/io.ts
src/utils/arweave.ts
tests/e2e/esm/index.test.js
tests/unit/utils.test.ts

TODO: 
- apis for updating delegates (ref: https://github.com/ar-io/ar-io-network-process/blob/develop/src/main.lua#L2913-L3009)

fix(PE-7080): add apis for fetching paginated delegates

---

README.md

This is to unblock the release v2.4.0

fix(types): add back delegates for AoGateway

---

src/common/io.ts
src/types/io.ts

Technically breaking - but should only impact arns.app

fix(arns): update reserved names to pagaination api

---

src/common/contracts/ao-process.ts
src/common/io.ts

Related - https://github.com/ar-io/ar-io-network-process/pull/205

fix(errors): we should be checking the result.Error as well as tags

---

README.md
src/common/ant.ts
src/types/ant.ts

Related https://github.com/ar-io/ar-io-ant-process/pull/36

fix: primary name continued

---

README.md
src/common/io.ts
src/types/common.ts
src/types/io.ts
tests/e2e/esm/index.test.js

this PR adds the Redelegate Stake write action and get redelegation fee read methods to the IO class

feat(redelegate stake): init IO methods PE-7159

---

README.md
src/common/io.ts
src/types/common.ts
src/types/io.ts

Related - https://github.com/ar-io/ar-io-network-process/pull/226

fix(io): updated types and fixed apis for primary name requests 

---

README.md

Co-locates relevant APIs for various features of the AR.IO contract

chore(docs): update README, organize APIs

---

README.md
src/common/io.ts
src/types/io.ts

fix(primary): support primary name in token cost API

---

CHANGELOG.md
README.md
package.json
src/common/ant.ts
src/common/io.ts
src/constants.ts
src/types/ant.ts
src/types/io.ts
src/version.ts
tests/e2e/esm/index.test.js

- use correct tag on setKeywords
- adds getGatewayRegistrySettings
- fix requestPrimaryName params in README 
- bump default ANT lua ID to ANT release 9 
- adds getDemandFactorSettings

chore: release 2.6.0

---

README.md
examples/esm/index.mjs
examples/vite/src/App.tsx
examples/web/index.html
examples/webpack/src/App.tsx
src/cli/cli.ts
src/cli/commands/gatewayWriteCommands.ts
src/cli/commands/readCommands.ts
src/cli/commands/transfer.ts
src/cli/options.ts
src/cli/types.ts
src/cli/utils.ts
src/common/ant.ts
src/common/io.ts
src/constants.ts
src/types/ant.ts
src/types/io.ts
src/types/token.ts
src/utils/processes.ts
tests/e2e/cjs/index.test.js
tests/e2e/esm/index.test.js
tests/e2e/web/src/App.tsx
tests/unit/token.test.ts

this is a breaking change, the IO class is now the ARIO class exported functions IOToken and mIOToken are now ARIOToken and mARIOToken
PE-7241

feat(ARIO token): change all IO references to ARIO

---

src/utils/ao.ts

https://docs.arconnect.io/api/sign-dataitem

fix(arconnect): use signDataItem method, signature is deprecated

---

CLI.md
README.md
src/cli/cli.ts
src/cli/commands/readCommands.ts
src/common/io.ts
src/types/io.ts
tests/e2e/esm/index.test.ts

```sh
> node lib/esm/cli/cli.js list-all-gateway-vaults --dev
{
"sortOrder": "desc",
"hasMore": false,
"totalItems": 5,
"limit": 10,
"sortBy": "startTimestamp",
"items": [
{
"vaultId": "UPl5eBrgVbr957P896x-_OAW3Ej9mRxK-4tRFZB3Hyo",
"startTimestamp": 1734063140256,
"gatewayAddress": "LtV0aSqgK3YI7c5FmfvZd-wG95TJ9sezj_a4syaLMS8",
"cursorId": "LtV0aSqgK3YI7c5FmfvZd-wG95TJ9sezj_a4syaLMS8_UPl5eBrgVbr957P896x-_OAW3Ej9mRxK-4tRFZB3Hyo",
"balance": 11000000,
"endTimestamp": 1741839140256
},
{
"vaultId": "PlfoTHBfR6EU8yGSFCyWAL1gN-cOgjNpPzjQJX-6VU4",
"startTimestamp": 1733815818611,
"gatewayAddress": "LtV0aSqgK3YI7c5FmfvZd-wG95TJ9sezj_a4syaLMS8",
"cursorId": "LtV0aSqgK3YI7c5FmfvZd-wG95TJ9sezj_a4syaLMS8_PlfoTHBfR6EU8yGSFCyWAL1gN-cOgjNpPzjQJX-6VU4",
"balance": 10000000,
"endTimestamp": 1741591818611 …
```

feat(api): support getAllGatewayVault API, init method, command, tests PE-7220

---

README.md
src/common/ant.ts
src/types/ant.ts

This is for better DX when manipulating records on ANTs

fix(ant): add setUndername and setBasename apis

---

CLI.md
README.md
src/cli/cli.ts
src/cli/commands/transfer.ts
src/cli/options.ts
src/cli/utils.ts
src/common/io.ts
src/types/ant.ts
src/types/common.ts
src/types/io.ts

```sh
> node lib/esm/cli/cli.js create-vault --wallet-file ../wallets/zarweave-keyfile-jaxl_dxqJ00gEgQazGASFXVRvO4h-Q0_vnaLtuOUoWU_dereks.json --quantity 100 --lock-length-ms 1209600000 --dev
✔ Are you sure you want to create a vault with 100 ARIO, locked for 1209600000ms? … yes
{
"senderAddress": "jaxl_dxqJ00gEgQazGASFXVRvO4h-Q0_vnaLtuOUoWU",
"transferResult": {
"id": "10FY_gfgiOTpdbz6yUv7xnkCtxnXzlDwa3iCii-V1oE",
"result": {
"balance": 100000000,
"startTimestamp": 1738260359944,
"endTimestamp": 1739469959944
}
},
"message": "Successfully created vault with 100 ARIO"
}
```
```sh
> node lib/esm/cli/cli.js get-vault --vault-id 10FY_gfgiOTpdbz6yUv7xnkCtxnXzlDwa3iCii-V1oE --address jaxl_dxqJ00gEgQazGASFXVRvO4h-Q0_vnaLtuOUoWU --dev
{
"balance": 100000000,
"startTimestamp": 1738260359944, …
```

feat(vault apis): init write methods+commands for create/extend/increase vault PE-7541

---

README.md
examples/cjs/index.cjs
examples/esm/index.mjs
src/cli/utils.ts
src/common/ant.ts
src/common/io.ts
src/utils/arweave.ts
src/utils/processes.ts

BREAKING CHANGE: SDK and CLI will not longer go to AR.IO Testnet by default

feat(mainnet): use mainnet process ID by default

---

tests/e2e/esm/index.test.ts

We will update these types separtely

chore(test): remove updated variables from tests

---

src/common/ant-versions.ts
src/common/io.ts
src/common/turbo.ts
src/types/common.ts
src/types/io.ts
src/utils/url.test.ts
src/utils/url.ts

Includes a more generic payment provider interface, consolidating types, and updates around calling turbo APIs.

chore(arns): some comments related to turbo integration

---

src/cli/commands/arnsPurchaseCommands.ts
src/cli/options.ts
src/cli/utils.ts
src/common/io.ts
src/common/turbo.ts
src/types/io.ts
src/utils/url.ts

```sh
node lib/esm/cli/cli.js buy-record --process-id ECHKeeR1S7_wsw3pcQdZNz2tNlXN_RyzUkzZokv4ssc --wallet-file ../wallets/eth.pk.0x02f40b84CdDe657245049476E1E01DDffde6a21c.txt --name turbo-credits-can-be-used-buy-arns-names-016  --skip-confirmation --debug --fund-from turbo --years 1 --token ethereum --payment-url https://payment.ardrive.dev --cu-url https://cu.ardrive.io --paid-by jaxl_dxqJ00gEgQazGASFXVRvO4h-Q0_vnaLtuOUoWU                                            
{"data":{"arioWriteResult":{"id":"nYJS1GzhOjflTtwx4VlDX5FRUa4WiixBFZoE2nuM7Z4","result":{"baseRegistrationFee":400000000,"endTimestamp":1779371854515,"name":"turbo-credits-can-be-used-buy-arns-names-016","processId":"ECHKeeR1S7_wsw3pcQdZNz2tNlXN_RyzUkzZokv4ssc","purchasePrice":488356799,"remainingBalance":49986434590590,"sta …
```

feat(arns): append paidBy to query params on fundfrom turbo arns purcahaes PE-7943

---

README.md
src/cli/commands/readCommands.ts
src/cli/options.ts
src/cli/utils.ts
src/common/io.ts
src/types/io.ts
src/utils/arweave.ts
tests/e2e/docker-compose.test.yml
tests/e2e/esm/index.test.ts

Related to https://github.com/ar-io/ar-io-network-process/pull/427 and depends on https://github.com/ar-io/ar-io-network-process/pull/429 getting applied to testnet/mainnet processes

feat(PE-8172): pagination filters
